### ISSUE TITLE
Objectif

### ISSUE THREAD

**Issue by DEKHTIARJonathan** [Pierre-Gilles/twitter-machine-learning#1]
Hey l'ami ;)

C'est quoi ton objectif exactement je peux peut-être t'aider j'avais deja fais pas mal de choses avec le ML et l'API Twitter ;)

**Comment by Pierre-Gilles** [comment]
L'objectif c'est surtout de s'amuser en plein finaux :D 

Pour l'instant le but c'est d'écouter tous les tweets en rapport avec un thème particulier (ici j'ai mis BigData, MachineLearning et DataScience pour rester dans le thème), les enregistrer dans une base (ici un MySQL) avec leurs hashtags. 

Je laisse tourner ça sur un serveur pendant un petit moment pour avoir un gros lot de données.

Et après je sais pas encore exactement, mais je pensais essayer de lancer un a-priori sur le lot de hashtag pour par exemple trouver des hashtags qui sont très souvent présents entre eux.. Voir des hashtags qui sont souvent présents à certains horaires, ou sur certains comptes Twitter. 

A vrai dire je sais pas encore totalement, j'ai lancé ça pour que ça mouline pendant les finaux et que j'ai mon lot pour m'amuser après :) Si t'as des idées de trucs funs à faire sur des tweets, ça m'intéresse toujours ! 

Sachant que l'objectif c'est de me faire la main ici pour pouvoir appliquer ça derrière à mon système domotique Gladys.

**Comment by DEKHTIARJonathan** [comment]
Il y a tout un tas de choses faissable comme un **social data dashboard** ou **trends dashboard** (plus spécifiquement lié au data).

Le tout est de pouvoir proposer un ensemble de data-viz web-based permettant de voir et détecter les nouveaux trend en rapport avec un sujet ;)

Je pense que concrètement si le service est bon ya certainement même de quoi en faire une startup ;)

**Comment by Pierre-Gilles** [comment]
C'est vrai, après il y a pas mal de services qui existent déjà ! 

Ce que je peux toujours faire, c'est un système qui apprend les caractéristiques des tweets qui buzz, et qui prédit un futur buzz, mais bon c'est du classique ça.

Ou alors un système qui combine des tweets entre eux ( genre les tweets qui ont un même lien, on les combine et on les tweets ), ça peut faire n'importe quoi mais ça peut être drôle.

Un détecteur d'influenceurs dans le milieu, genre les mecs qui tweet en premier une infos et qui se font reprendre.
